<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//input[contains(@class,'gLFyf')]</description>
   <name>input_Buscar</name>
   <tag></tag>
   <elementGuidId>4b195e0e-b50a-4a57-b353-a17c140f61a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@class,'gLFyf')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
